// Python `str` behaviour that the terminal output depends on: what counts as whitespace, lengths
// in code points (Python) rather than UTF-16 units (JavaScript), and textwrap.wrap().

// str.isspace(), str.split(), str.strip() and the regex class \s all use this set in Python.
// JavaScript's \s differs: it adds U+FEFF and leaves out U+001C-U+001F and U+0085.
export const PY_SPACE_CLASS =
  "\\t\\n\\x0b\\x0c\\r\\x1c-\\x20\\x85\\xa0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000";

// Python 3.12 matches \w against Unicode 15.0; Node 22 knows Unicode 17.0. Python's \w is exactly
// JavaScript's [\p{L}\p{N}_] minus the code points assigned after 15.0, listed here (generated by
// comparing both engines over every code point). On a Node with an older Unicode table these
// ranges are unassigned, so excluding them changes nothing.
const NEWER_THAN_PYTHON =
  "[\\u088f\\u0c5c\\u0cdc\\u1c89-\\u1c8a\\ua7cb-\\ua7cf\\ua7d2\\ua7d4\\ua7da-\\ua7f1" +
  "\\u{105c0}-\\u{105f3}\\u{10940}-\\u{10959}\\u{10d40}-\\u{10d85}\\u{10ec2}-\\u{10ec7}" +
  "\\u{11380}-\\u{113d3}\\u{116d0}-\\u{116e3}\\u{11bc0}-\\u{11bf9}\\u{11db0}-\\u{11de9}" +
  "\\u{13460}-\\u{143fa}\\u{16100}-\\u{16139}\\u{16d40}-\\u{16d79}\\u{16ea0}-\\u{16ed3}" +
  "\\u{16ff2}-\\u{16ff6}\\u{187f8}-\\u{187ff}\\u{18cff}\\u{18d09}-\\u{18df2}" +
  "\\u{1ccf0}-\\u{1ccf9}\\u{1e5d0}-\\u{1e6ff}\\u{2b73a}-\\u{2b73f}\\u{2cea2}-\\u{2cead}" +
  "\\u{2ebf0}-\\u{2ee5d}\\u{323b0}-\\u{33479}]";

/** One Python `\w` character, for a RegExp built with the `u` flag. */
export const PY_WORD = `(?:(?!${NEWER_THAN_PYTHON})[\\p{L}\\p{N}_])`;
/** One Python `\d` character (Unicode category Nd), for a RegExp built with the `u` flag. */
export const PY_DIGIT = `(?:(?!${NEWER_THAN_PYTHON})\\p{Nd})`;

const SPACE_RUN = new RegExp(`[${PY_SPACE_CLASS}]+`, "u");
const LEADING_SPACE = new RegExp(`^[${PY_SPACE_CLASS}]+`, "u");
const TRAILING_SPACE = new RegExp(`[${PY_SPACE_CLASS}]+$`, "u");
const SURROGATE = /[\ud800-\udfff]/;

/** len(s): the number of code points. */
export function cpLength(s) {
  if (!SURROGATE.test(s)) return s.length;
  let n = 0;
  for (const _ of s) n += 1;
  return n;
}

/** s[start:end] for non-negative start and end, counted in code points. */
export function cpSlice(s, start, end = Infinity) {
  if (!SURROGATE.test(s)) return s.slice(start, end);
  return Array.from(s).slice(start, end).join("");
}

/** s.split() with no arguments. */
export function pySplit(s) {
  return s.split(SPACE_RUN).filter((part) => part !== "");
}

/** s.strip() with no arguments. */
export function pyStrip(s) {
  return s.replace(LEADING_SPACE, "").replace(TRAILING_SPACE, "");
}

/** s.rstrip() with no arguments. */
export function pyRstrip(s) {
  return s.replace(TRAILING_SPACE, "");
}

/** s.expandtabs(tabsize): the column restarts after \n and \r, and counts code points. */
export function expandTabs(s, tabsize = 8) {
  if (!s.includes("\t")) return s;
  let out = "";
  let column = 0;
  for (const ch of s) {
    if (ch === "\t") {
      if (tabsize > 0) {
        const incr = tabsize - (column % tabsize);
        out += " ".repeat(incr);
        column += incr;
      }
    } else {
      out += ch;
      column = ch === "\n" || ch === "\r" ? 0 : column + 1;
    }
  }
  return out;
}

// textwrap.TextWrapper's two chunking regexes. The whitespace here is ASCII only, on purpose
// (textwrap keeps non-breaking spaces inside words).
const WS = "[\\t\\n\\x0b\\x0c\\r ]";
const NWS = "[^\\t\\n\\x0b\\x0c\\r ]";
const WORD_PUNCT = `(?:${PY_WORD}|[!"'&.,?])`;
const LETTER = `(?:(?!\\p{Nd})${PY_WORD})`; // [^\d\W]
const WORDSEP = new RegExp(
  `(${WS}+` +
    `|(?<=${WORD_PUNCT})-{2,}(?=${PY_WORD})` +
    `|${NWS}+?(?:` +
    `-(?:(?<=${LETTER}{2}-)|(?<=${LETTER}-${LETTER}-))(?=${LETTER}-?${LETTER})` +
    `|(?=${WS}|$)` +
    `|(?<=${WORD_PUNCT})(?=-{2,}${PY_WORD})` +
    "))",
  "gu",
);
const WORDSEP_SIMPLE = new RegExp(`(${WS}+)`, "gu");
const MUNGED_WHITESPACE = /[\t\n\x0b\x0c\r]/g;

function splitKeepingSeparators(text, pattern) {
  const parts = [];
  let last = 0;
  for (const match of text.matchAll(pattern)) {
    parts.push(text.slice(last, match.index), match[1]);
    last = match.index + match[0].length;
  }
  parts.push(text.slice(last));
  return parts.filter((part) => part !== "");
}

/**
 * textwrap.wrap(text, width, initial_indent=..., subsequent_indent=..., break_on_hyphens=...)
 * with every other TextWrapper option at its default (expand_tabs, replace_whitespace,
 * break_long_words and drop_whitespace on; fix_sentence_endings and max_lines off).
 */
export function wrap(text, width, options = {}) {
  const initialIndent = options.initialIndent ?? "";
  const subsequentIndent = options.subsequentIndent ?? "";
  const breakOnHyphens = options.breakOnHyphens ?? true;
  if (width <= 0) throw new RangeError(`invalid width ${width} (must be > 0)`);

  const munged = expandTabs(text, 8).replace(MUNGED_WHITESPACE, " ");
  const chunks = splitKeepingSeparators(munged, breakOnHyphens ? WORDSEP : WORDSEP_SIMPLE);
  chunks.reverse();

  const lines = [];
  while (chunks.length) {
    const curLine = [];
    let curLen = 0;
    const indent = lines.length ? subsequentIndent : initialIndent;
    const lineWidth = width - cpLength(indent);

    // A whitespace chunk at the start of any line but the first is dropped.
    if (pyStrip(chunks[chunks.length - 1]) === "" && lines.length) chunks.pop();

    while (chunks.length) {
      const len = cpLength(chunks[chunks.length - 1]);
      if (curLen + len > lineWidth) break;
      curLine.push(chunks.pop());
      curLen += len;
    }

    if (chunks.length && cpLength(chunks[chunks.length - 1]) > lineWidth) {
      handleLongWord(chunks, curLine, curLen, lineWidth, breakOnHyphens);
      curLen = curLine.reduce((sum, chunk) => sum + cpLength(chunk), 0);
    }

    if (curLine.length && pyStrip(curLine[curLine.length - 1]) === "") {
      curLen -= cpLength(curLine.pop());
    }

    if (curLine.length) lines.push(indent + curLine.join(""));
  }
  return lines;
}

function handleLongWord(reversedChunks, curLine, curLen, width, breakOnHyphens) {
  const spaceLeft = width < 1 ? 1 : width - curLen;
  const chunk = Array.from(reversedChunks[reversedChunks.length - 1]);
  let end = spaceLeft;
  if (breakOnHyphens && chunk.length > spaceLeft) {
    // chunk.rfind('-', 0, space_left): break after the last hyphen that has a non-hyphen
    // somewhere before it.
    // (A negative fromIndex would make lastIndexOf search from the end, so guard 0.)
    const hyphen = spaceLeft > 0 ? chunk.lastIndexOf("-", Math.min(spaceLeft, chunk.length) - 1) : -1;
    if (hyphen > 0 && chunk.slice(0, hyphen).some((c) => c !== "-")) end = hyphen + 1;
  }
  curLine.push(chunk.slice(0, end).join(""));
  reversedChunks[reversedChunks.length - 1] = chunk.slice(end).join("");
}
